import Head from 'next/head'
import Image from 'next/image'
import Homepage from '../components/Homepage'

export default function Home() {
  return (
    <div className="dark:bg-darkBg bg-white">
      <Head>
        <title>Digift Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Homepage />

    </div>
  )
}
